import { createAction } from 'redux-actions';

export const FETCH_BOOKS_REQUEST = 'FETCH_BOOKS_REQUEST';
export const FETCH_GENRES_REQUEST = 'FETCH_GENRES_REQUEST';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
export const FETCH_BOOKS_ERROR = 'FETCH_BOOKS_ERROR';
export const BOOK_UPDATE = 'BOOK_UPDATE';
export const SAGA_BOOK_UPDATE = 'SAGA_BOOK_UPDATE';
export const BOOK_DELETE = 'BOOK_DELETE';
export const SAGA_BOOK_DELETE = 'SAGA_BOOK_DELETE';
export const BOOK_SET_GENRES = 'BOOK_SET_GENRES';
export const BOOK_ADD = 'BOOK_ADD';
export const SAGA_BOOK_ADD = 'SAGA_BOOK_ADD';
export const SET_DATE_FILTER_SAGA = 'SET_DATE_FILTER_SAGA';
export const SET_DATE_FILTER = 'SET_DATE_FILTER';

export const fetchBooksRequest = createAction(FETCH_BOOKS_REQUEST);
export const fetchBooksSuccess = createAction(FETCH_BOOKS_SUCCESS);
export const fetchBooksError = createAction(FETCH_BOOKS_ERROR);
export const bookUpdate = createAction(BOOK_UPDATE);
export const sagaBookUpdate = createAction(SAGA_BOOK_UPDATE);
export const bookDelete = createAction(BOOK_DELETE);
export const sagaBookDelete = createAction(SAGA_BOOK_DELETE);
export const bookSetGenres = createAction(BOOK_SET_GENRES);
export const bookAdd = createAction(BOOK_ADD);
export const sagaBookAdd = createAction(SAGA_BOOK_ADD);
export const fetchGenresRequest = createAction(FETCH_GENRES_REQUEST);
export const fetchGenresSuccess = createAction(FETCH_GENRES_SUCCESS);
export const setDateFilterSaga = createAction(SET_DATE_FILTER_SAGA);
export const setDateFilter = createAction(SET_DATE_FILTER);
